const promocodes = {
  pogrebjiskaya: 'Погребижская',
  alex4planet: 'ПЛАНЕТА',
  porakpsihologu: 'Пора к Психологу',
  muradimovaalina: 'АЛИНА10',
  maniloun: 'MANILOUN',
  neprinyato: 'НЕ ПРИНЯТО ОБСУЖДАТЬ',
  retrograd29: 'МЕРКУРИЙ',
  globa: 'ГЛОБА',
  uzefovich: 'ЮЗЕФОВИЧ',
  shahimat: 'Шах и Мат',
  eninaanna: 'ЕНИНА',
  dashtolc: 'dashatolc',
  sobchak: 'СОБЧАК',
  sulim: 'СУЛИМ',
  strelezc: 'СТРЕЛЕЦ',
  pubum: 'СТРЕЛЕЦ',
  christiagata: 'АГАТАКРИСТИ',
  mashnews4: 'MASH',
  alexandraposnova: 'ПОСНОВА',
  pogrebjiskaya2: 'Погребижская',
  irenaponaroshku: 'Ирена',
  morskaya: 'МОРСКАЯ',
  // veronikastepanova20011: 'СТЕПАНОВА',
  sobchak0702: 'Собчак',
  vasilisavolodinaofficial: 'ВАСИЛИСА',
  dorogedeneg: 'ДОРОЖЕ',
  '1000idey2': '1000',
  tanyamint: 'MINT',
  dukalis: 'ДУКАЛИС',
  planetaalex: 'ПЛАНЕТА',
  hotpsyhologies: 'ВИКТОРИЯ',
  pogrebjiskaya3: 'Погребижская',
  annashow: 'АННА ШОУ',
  Barabanshchykava: 'ЛИЗА МАТРИКС',
  angelapodcast: 'Секс и деньги',
  likapsychology: 'ЛИКА10',
  julso:'ДЖУЛСО',
  karina_che: 'КАРИНА',
  matilda: 'МАТИЛЬДА',
  polyanka: 'ПОЛЯНКА',
  alena_ily: 'АЛЕНА',
  poechka: 'ПОЕЧКА',
  ginevskaya: 'ГИНЕВСКАЯ',
  arinahlus: 'АРИНА',
  prohorshalyzpin: 'СЧАСТЬЕ',
  sanya_florida: 'САНЯ',
  'liz.zolotareva': 'ЗОЛОТАРЕВА',
  moscowmap: 'moscowmap',
  moguchaya: 'МОГУЧАЯ',
  kydriwa2403: 'KYDRIWA',
  neeshpapa: 'ДОКТОР25',
  vodnay: 'ВОДНАЯ',
  // millonshchiki: 'МИЛЛИОН',
  Drobyshevskaia:'Maria D',
  karpavichus: 'АРТЕМ10',
  defiendidiana2: 'DEF',
  agibalova: 'агибалова',
  nataliaremish: 'РЕМИШ',
  'doctor.artempark': 'ПАК',
  davay: 'ДАВАЙ',
  natasakado: 'САКАДО'
}

export default promocodes
