const promocodesWithGift = {
  alexandraposnova: { gift: 'https://mipinstitute.getcourse.ru/podp_mini_two' },
  pogrebjiskaya2: { gift: 'https://mipinstitute.getcourse.ru/podp_mini_two' },
  irenaponaroshku: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  morskaya: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  veronikastepanova20011: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  sobchak0702: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  vasilisavolodinaofficial: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  dorogedeneg: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  '1000idey2': { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  tanyamint: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  dukalis: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  planetaalex: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  porakpsihologu: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  hotpsyhologies: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  pogrebjiskaya3: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  annashow: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  Barabanshchykava: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  pogrebjiskaya: { gift: 'https://mipinstitute.getcourse.ru/podp_mini_two' },
  angelapodcast: { gift: 'https://mipinstitute.getcourse.ru/podp_mini_two' },
  likapsychology: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  julso: { gift: 'https://mip.institute/free-access' },
  karina_che: { gift: 'https://mip.institute/free-access' },
  matilda: { gift: 'https://mip.institute/free-access' },
  polyanka: { gift: 'https://mip.institute/free-access' },
  alena_ily: { gift: 'https://mip.institute/free-access' },
  poechka: { gift: 'https://mip.institute/free-access' },
  ginevskaya: { gift: 'https://mip.institute/free-access' },
  arinahlus: { gift: 'https://mip.institute/free-access' },
  prohorshalyzpin: { gift: 'https://mip.institute/free-access' },
  sanya_florida:  { gift: 'https://mip.institute/free-access' },
  'liz.zolotareva':  { gift: 'https://mip.institute/free-access' },
  moscowmap:  { gift: 'https://mip.institute/free-access' },
  moguchaya: { gift: 'https://mipinstitute.getcourse.ru/podp_mini_two' },
  kydriwa2403: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  neeshpapa: { gift: 'https://mip.institute/free-access' },
  vodnay: { gift: 'https://mip.institute/free-access' },

  neprinyato: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  // millonshchiki: { gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  Drobyshevskaia:{ gift: 'https://mipinstitute.getcourse.ru/3shaga_dostup' },
  karpavichus:{ gift: 'https://mip.institute/free-access' },
  agibalova: { gift: 'https://mip.institute/free-access' },
  nataliaremish: { gift: 'https://mip.institute/free-access' },
  'doctor.artempark': { gift: 'https://mip.institute/free-access' },
  davay: { gift: 'https://mip.institute/free-access' },
  retrogradnymercury: { gift: 'https://mip.institute/free-access' },
  merkury_may: { gift: 'https://mip.institute/free-access' },
  natasakado: { gift: 'https://mip.institute/free-access' },
}

export default promocodesWithGift
