import { Analytics } from "@vercel/analytics/react"
import { ContextStaticProps } from "../context"
import MenuState from "@/context/menu/MenuState"
import FieldsTooltipState from "@/context/fieldsTooltip/FieldsTooltipState"
import StickyTop from "@/components/sections/StickyTop"
import Header from "@/components/sections/Header"
import { ApolloProvider } from "@apollo/client"
import StickyBottom from "@/components/sections/StickyBottom"
import Footer from "@/components/sections/Footer"
import '@/styles/app.sass'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
              <body>
      
        <MenuState>
          <FieldsTooltipState>
            {/* <div className={promo ? 'fullContainerWithPromo fullContainer' : 'fullContainer'}> */}
            
              {/* <StickyTop
                isWithGift={isWithGift}
                onClick={closePromo}
                isPromo={isPromo}
                promoText={promoText}
              /> */}
            
            
              <Header  />
                {children}
            <Footer />

            <div><StickyBottom /></div>
            {/* </div> */}
          </FieldsTooltipState>
        </MenuState>
      <Analytics />
      </body>
      
    </html>
  )
}
